services:
  taskmanagement-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanagement-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__TaskManagementConnection=Server=sqlserver;Database=TaskManagement;User Id=sa;Password=task@Passw0rd;TrustServerCertificate=true;
      - Jwt__Key=Task-Management-Tam-Assessment-Sarah
      - Jwt__Issuer=TaskManagementAPI
      - Jwt__Audience=TaskManagementClients
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
    networks:
      - taskmanagement-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=task@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - taskmanagement-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  taskmanagement-network:
    driver: bridge